In [2]:
import pandas as pd

In [16]:
df = pd.read_csv('transactions.csv')

df = df.drop(df.columns[[1,4,5,8]], axis=1) #drop the Reference ID, Till No, Account No and MM System columns
df.head()

,Date,Sender Identifier,Name,Fees (KSh),Amount (KSh),Status
0,29/03/2019 15:19,2.54707E+11,RAMADHAN MWENDA,0.0,20,Complete
1,29/03/2019 18:49,2.54757E+11,HOSEA KIHARA,0.0,200,Complete
2,29/03/2019 19:42,2.54707E+11,RAMADHAN MWENDA,0.0,20,Complete
3,30/03/2019 15:41,2.54714E+11,ABIGAIL MUNENE,0.0,70,Complete
4,03/04/2019 11:39,2.54795E+11,IAN MUKUNDI,0.0,20,Complete

In [21]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst='True') #convert the Date column to datetime

In [24]:
df['Time'] = df['Date'].dt.time #extract the time from the Date column
df['Date'] = df['Date'].dt.date #extract the date from the Date column
df.head()

,Date,Sender Identifier,Name,Fees (KSh),Amount (KSh),Status,Time
0,2019-03-29,2.54707E+11,RAMADHAN MWENDA,0.0,20,Complete,15:19:00
1,2019-03-29,2.54757E+11,HOSEA KIHARA,0.0,200,Complete,18:49:00
2,2019-03-29,2.54707E+11,RAMADHAN MWENDA,0.0,20,Complete,19:42:00
3,2019-03-30,2.54714E+11,ABIGAIL MUNENE,0.0,70,Complete,15:41:00
4,2019-04-03,2.54795E+11,IAN MUKUNDI,0.0,20,Complete,11:39:00

In [30]:
df = df.rename(columns={'Sender Identifier': 'ID'})
df = df.rename(columns={'Fees (KSh)': 'Fees'})
df = df.rename(columns={'Amount (KSh)': 'Amount'})
df.head()

         Date           ID             Name  Fees Amount    Status      Time
0  2019-03-29  2.54707E+11  RAMADHAN MWENDA   0.0     20  Complete  15:19:00
1  2019-03-29  2.54757E+11     HOSEA KIHARA   0.0    200  Complete  18:49:00
2  2019-03-29  2.54707E+11  RAMADHAN MWENDA   0.0     20  Complete  19:42:00
3  2019-03-30  2.54714E+11   ABIGAIL MUNENE   0.0     70  Complete  15:41:00
4  2019-04-03  2.54795E+11      IAN MUKUNDI   0.0     20  Complete  11:39:00

In [ ]:
df = df.astype({'ID': str, 'Name': str, 'Fees':float}) #convert the ID and Name columns to string and the Fees and Amount columns to float
df.dtypes

Date       object
ID         object
Name       object
Fees      float64
Amount     object
Status     object
Time       object
dtype: object

In [ ]:
df['Amount'] = df['Amount'].str.replace(',','')
df['Amount'] = df['Amount'].astype(float) #convert the Amount column to float

In [ ]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst='True') #convert the Date column to datetime
df.dtypes

Date      datetime64[ns]
ID                object
Name              object
Fees             float64
Amount           float64
Status            object
Time              object
dtype: object

In [50]:
df['Time'] = df['Time'].astype(str) #convert the Time column to string
df['Time'] = pd.to_datetime(df['Time'], format='%H:%M:%S') #convert the Time column to time

df.dtypes

Date      datetime64[ns]
ID                object
Name              object
Fees             float64
Amount           float64
Status            object
Time      datetime64[ns]
dtype: object