## Exploratory Data Analysis for the Sankofa App

In [1]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [7]:
# Read the data into the Notebook
df = pd.read_csv("D:\DSA Project\Sankofa_App\Data/transactions_report_2015-01-08_to_2024-12-31.csv")
df.head()

,Date,Reference ID,Sender Identifier,Name,Till No.,Account Number,Fees (KSh),Amount (KSh),MM System,Status
0,29/03/2019 15:19,NCT7TV33DD,2.54707E+11,RAMADHAN MWENDA,632868,NaN,0.0,20,M-PESA,Complete
1,29/03/2019 18:49,NCT9U2D7Y3,2.54757E+11,HOSEA KIHARA,632868,NaN,0.0,200,M-PESA,Complete
2,29/03/2019 19:42,NCT4U4TMV8,2.54707E+11,RAMADHAN MWENDA,632868,NaN,0.0,20,M-PESA,Complete
3,30/03/2019 15:41,NCU3URX7A1,2.54714E+11,ABIGAIL MUNENE,632868,NaN,0.0,70,M-PESA,Complete
4,03/04/2019 11:39,ND39XXKTYF,2.54795E+11,IAN MUKUNDI,632868,NaN,0.0,20,M-PESA,Complete

In [ ]:
# Checking descriptive statistics
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Date,11485,11373,05/12/2023 11:45,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Reference ID,11485,11485,SLV5HDP7Z3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sender Identifier,11485,1324,2.54722E+11,883,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Name,11485,5065,WILLIAM MWINGA,193,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Till No.,11485.0,NaN,NaN,NaN,632868.0,0.0,632868.0,632868.0,632868.0,632868.0,632868.0
Account Number,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fees (KSh),11485.0,NaN,NaN,NaN,0.428974,1.69443,0.0,0.0,0.0,0.0,67.65
Amount (KSh),11485,235,20,2551,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MM System,11485,1,M-PESA,11485,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Status,11485,3,Complete,11471,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.shape

(11485, 10)